# Generated by Django 4.2.16 on 2024-10-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('tittle', models.CharField(max_length=255)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
