# Generated by Django 4.2.16 on 2024-10-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_login_delete_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='tittle',
            new_name='title',
        ),
    ]
